### ISSUE TITLE
Having the post date in your CSV header is misleading.

### ISSUE THREAD

**Issue by Dan-Avel** [siddweiker/chase2csv#1]
I was getting started making use of your module. When I looked at your README and was concerned that perhaps this project may not be compatible with Chase Bank's current statements. I couldn't find any indication of a post date in my PDF. This is because Chase doesn't include a post date in their statements. Line 115 of chase2csv.py populates the post date column with an empty string. Removing that column or stating that it's not populated would reduce confusion.

**Comment by siddweiker** [comment]
This script is no longer required because you can download transactions as CSVs now.
